# -*- coding: utf-8 -*-
"""Copy and offer config for Heaterax / AirCurtain GEO landings."""

UID = "0197a185-b0bf-7062-9c73-c30ab45065b7"
WEBHOOK = "https://hook.eu2.make.com/p379ghguoxvm0qnbwyb6ij9e2shqjphq"
FORM_ACTION = "https://offers.adricenetwork.com/forms/html/"

OFFERS = [
    {
        "geo": "ro",
        "slug": "wall-convector-1244",
        "product_type": "wall",
        "offer_id": "1244",
        "lp_id": "1263",
        "form_key": "cb42e181496cbb44a7f6385f805d500d47a11a49",
        "form_submit": "COMANDA ACUM",
        "form_fields": [
            {"name": "name", "label": "Nume și prenume*", "placeholder": "Nume și prenume", "type": "text", "autocomplete": "name", "required": True},
            {"name": "tel", "label": "Telefon*", "placeholder": "Telefon", "type": "tel", "autocomplete": "tel", "required": True},
            {"name": "street-address", "label": "Adresă completă*", "placeholder": "Adresă completă", "type": "text", "autocomplete": "street-address", "required": True},
        ],
        "currency": "RON",
        "price": 397.0,
        "price_now": "397 lei",
        "price_was": "794 lei",
        "meta_cpa": 14.0,
        "lang": "ro",
        "locale_key": "ro",
    },
    {
        "geo": "pt",
        "slug": "air-curtain-1673",
        "product_type": "curtain",
        "offer_id": "1673",
        "lp_id": "1693",
        "form_key": "be913d0ad0a2ab42a6a9f95008d8d58b7f048977",
        "form_submit": "Encomendar agora",
        "form_fields": [
            {"name": "name", "label": "Nome próprio Apelido*", "placeholder": "Nome próprio Apelido", "type": "text", "autocomplete": "name", "required": True},
            {"name": "street-address", "label": "Endereço*", "placeholder": "Endereço", "type": "text", "autocomplete": "street-address", "required": True},
            {"name": "tel", "label": "Telefone de contacto*", "placeholder": "Telefone de contacto", "type": "tel", "autocomplete": "tel", "required": True},
        ],
        "currency": "EUR",
        "price": 89.0,
        "price_now": "89 €",
        "price_was": "178 €",
        "meta_cpa": 13.0,
        "lang": "pt",
        "locale_key": "pt",
    },
    {
        "geo": "pl",
        "slug": "wall-convector-1739",
        "product_type": "wall",
        "offer_id": "1739",
        "lp_id": "1759",
        "form_key": "d5bccb454f2625a4d768f90e5fed2fd972c853e7",
        "form_submit": "Zamów teraz",
        "form_fields": [
            {"name": "name", "label": "Imię i nazwisko*", "placeholder": "Imię i nazwisko", "type": "text", "autocomplete": "name", "required": True},
            {"name": "tel", "label": "Telefon*", "placeholder": "Telefon", "type": "tel", "autocomplete": "tel", "required": True},
            {"name": "street-address", "label": "Adres*", "placeholder": "Adres", "type": "text", "autocomplete": "street-address", "required": True},
            {"name": "postal-code", "label": "Kod pocztowy*", "placeholder": "Kod pocztowy", "type": "text", "autocomplete": "postal-code", "required": True},
            {"name": "address-level2", "label": "Miasto", "placeholder": "Miasto", "type": "text", "autocomplete": "address-level2", "required": False},
        ],
        "currency": "PLN",
        "price": 299.0,
        "price_now": "299 zł",
        "price_was": "598 zł",
        "meta_cpa": 13.0,
        "lang": "pl",
        "locale_key": "pl",
    },
    {
        "geo": "es",
        "slug": "air-curtain-2283",
        "product_type": "curtain",
        "offer_id": "2283",
        "lp_id": "2308",
        "form_key": "59d3889553a22b6a3cf6240613a518e00a9c4071",
        "form_submit": "Haz tu pedido",
        "form_fields": [
            {"name": "name", "label": "Nombre Apellido*", "placeholder": "Nombre Apellido", "type": "text", "autocomplete": "name", "required": True},
            {"name": "street-address", "label": "Dirección*", "placeholder": "Dirección", "type": "text", "autocomplete": "street-address", "required": True},
            {"name": "tel", "label": "Teléfono*", "placeholder": "Teléfono", "type": "tel", "autocomplete": "tel", "required": True},
        ],
        "currency": "EUR",
        "price": 89.0,
        "price_now": "89 €",
        "price_was": "178 €",
        "meta_cpa": 13.0,
        "lang": "es",
        "locale_key": "es",
    },
    {
        "geo": "de",
        "slug": "air-curtain-2285",
        "product_type": "curtain",
        "offer_id": "2285",
        "lp_id": "2310",
        "form_key": "f8e9e27e8af0efa942ab1616ad673ffb8afcb8cd",
        "form_submit": "Jetzt bestellen",
        "form_fields": [
            {"name": "name", "label": "Vorname Nachname*", "placeholder": "Vorname Nachname", "type": "text", "autocomplete": "name", "required": True},
            {"name": "street-address", "label": "Adresse*", "placeholder": "Adresse", "type": "text", "autocomplete": "street-address", "required": True},
            {"name": "tel", "label": "Telefon*", "placeholder": "Telefon", "type": "tel", "autocomplete": "tel", "required": True},
        ],
        "currency": "EUR",
        "price": 89.0,
        "price_now": "89 €",
        "price_was": "178 €",
        "meta_cpa": 14.0,
        "lang": "de",
        "locale_key": "de",
    },
    {
        "geo": "hu",
        "slug": "wall-convector-2919",
        "product_type": "wall",
        "offer_id": "2919",
        "lp_id": "2952",
        "form_key": "e3ba46f48043a07bef9da550e11a843ad1eab2b6",
        "form_submit": "Rendeljen most",
        "form_fields": [
            {"name": "name", "label": "Keresztnév Vezetéknév*", "placeholder": "Keresztnév Vezetéknév", "type": "text", "autocomplete": "name", "required": True},
            {"name": "street-address", "label": "Cím*", "placeholder": "Cím", "type": "text", "autocomplete": "street-address", "required": True},
            {"name": "tel", "label": "Telefon*", "placeholder": "Telefon", "type": "tel", "autocomplete": "tel", "required": True},
        ],
        "currency": "HUF",
        "price": 29999.0,
        "price_now": "29 999 Ft",
        "price_was": "59 998 Ft",
        "meta_cpa": 14.0,
        "lang": "hu",
        "locale_key": "hu",
    },
]

COPY = {
    "ro": {
        "brand": "Heaterax™",
        "header_line1": "Climatizator",
        "title": "Heaterax™ — Mini climatizator de perete 2în1 cald/rece | -50%",
        "meta_desc": "Heaterax™: climatizator compact 2în1, FastHeating, clasă A++++, plată ramburs în România.",
        "ticker_pay": "PLATĂ",
        "ticker_cod": "PLĂTEȘTI LA LIVRARE",
        "ticker_guarantee": "GARANȚIE",
        "ticker_refund": "SATISFACȚIE SAU BANII ÎNAPOI · 14 ZILE",
        "reviews_link": "★ Recenzii",
        "order_cta": "↗ Comandă acum",
        "h1": "Climatizatorul compact inovator fără unitate exterioară 2în1 care răcește vara și încălzește iarna, fără instalări costisitoare!",
        "lead": "Tehnologia <strong>FastHeating</strong> distribuie rapid aerul în fiecare cameră pentru o temperatură uniformă și confortabilă. Clasa <strong>A++++</strong> reduce consumul, iar funcționarea <strong>ultra-silentioasă</strong> asigură confort maxim zi și noapte.",
        "checklist": [
            "Încălzește sau răcește până la 120 m² în 8 minute",
            "Consumă doar 3,75 lei pe zi, clasă A++++",
            "Se montează în mai puțin de 2 minute, fără tehnician",
            "Design compact, doar 55 cm lățime",
            "Funcționează fără unitate exterioară și fără tub de evacuare",
            "FastHeating aduce rapid ambientul la temperatura setată",
            "Ultra-silentios pentru confort maxim și noaptea",
            "Filtru HEPA lavabil — reține 99,99% din germeni și bacterii",
            "Control simplu prin aplicația oficială sau telecomandă",
            "Rezervor de condens 10 L, ușor de golit",
        ],
        "rating": "Evaluare medie: <strong>4,8 / 5</strong> · peste <strong>4.200</strong> recenzii verificate",
        "countdown_label": "● OFERTĂ LIMITATĂ",
        "countdown_sub": "Se termină la <strong>23:59</strong> astăzi",
        "offer_h2": "Doar azi climatizatorul <span class=\"brand\">Heaterax™</span>",
        "offer_sub": "🚚 Livrare 24/48h + Garanție satisfăcut sau rambursat 14 zile",
        "price_label": "Doar",
        "discount": "− 50% reducere",
        "scroll_hint": "Completează formularul de mai jos pentru a comanda",
        "stock_badge": "STOC LIMITAT",
        "stock_warn": "<strong>Grăbește-te:</strong> au rămas doar <strong>18 bucăți</strong> în stoc!",
        "live": "<strong>{n} persoane</strong> comandă Heaterax acum",
        "form_h3": "Completează formularul de comandă",
        "form_intro": "Te contactăm pentru a confirma livrarea și plata ramburs.",
        "label_name": "Nume și prenume*",
        "label_tel": "Telefon mobil*",
        "label_addr": "Adresa de livrare*",
        "ph_name": "Ana Popescu",
        "ph_tel": "+40 722 123 456",
        "ph_addr": "Str. Victoriei 10, 010096 București",
        "submit": "Confirmă comanda",
        "form_trust": "🔒 Date protejate · Fără plată online · Livrare 24/48h",
        "trust1": "🛡️ Plată la livrare",
        "trust2": "🚚 Livrare 24/48h",
        "trust3": "↩️ Retur gratuit",
        "story1_eyebrow": "01 — Confort în doar 13 minute",
        "story1_h3": "Cald iarna, răcoare vara — fără așteptare",
        "story1_p1": "<strong>Heaterax™</strong> este un sistem compact de climatizare proiectat să încălzească sau răcească spații de până la <strong>85 m²</strong> în doar <strong>13 minute</strong>. Tehnologia <strong>FastHeating</strong> distribuie rapid aerul pentru confort uniform.",
        "story1_p2": "Setezi temperatura dorită, iar <strong>Heaterax™</strong> menține confortul rapid în tot apartamentul.",
        "story2_eyebrow": "02 — Montaj rapid",
        "story2_h3": "Fără instalări complicate",
        "story2_p1": "Uită de lucrări costisitoare și tehnicieni. Cu <strong>kitul de montaj rapid</strong>, <strong>Heaterax™</strong> se montează în mai puțin de <strong>2 minute</strong>.",
        "story2_p2": "Funcționează <strong>fără unitate exterioară</strong> și <strong>fără tub de evacuare</strong> — ideal în apartamente.",
        "story3_eyebrow": "03 — Control și întreținere",
        "story3_h3": "Control complet și simplu",
        "story3_p1": "Reglezi temperatura de pe canapea cu <strong>telecomanda inclusă</strong> sau <strong>aplicația oficială Heaterax™</strong>. <strong>Display LED</strong> și <strong>timer</strong> integrate.",
        "story3_p2": "Rezervorul de condens de <strong>10 litri</strong> este ușor de golit.",
        "reviews_h2": "Recenzii clienți",
        "reviews_sub": "★ 4,8/5 · Achiziție verificată",
        "rev1_h": "Montat singură, căldura se simte imediat",
        "rev1_p": "«L-am montat singură, fără tehnician. Diferența de temperatură se simte rapid, iar în apartamentul din Cluj ocupă mult mai puțin spațiu decât mă așteptam.»",
        "rev1_a": "Ana M. ✅ — Cluj-Napoca · Achiziție verificată",
        "rev2_h": "Silențios în dormitor, comod din pat",
        "rev2_p": "«Îl folosesc seara în dormitor din Timișoara și este surprinzător de silențios. Telecomanda e simplă — reglez temperatura fără să mă ridic.»",
        "rev2_a": "Andrei P. ✅ — Timișoara · Achiziție verificată",
        "rev3_h": "Fără unitate exterioară, montaj simplu",
        "rev3_p": "«L-am ales pentru că nu necesită unitate exterioară. Montajul în Iași a fost simplu, fără găuri mari sau lucrări complicate.»",
        "rev3_a": "Ioana D. ✅ — Iași · Achiziție verificată",
        "kit_eyebrow": "Ce primești azi",
        "kit_h2": "Kit complet Heaterax™",
        "kit_li1": "<strong>1× Heaterax™</strong> mini climatizator 2în1 de perete",
        "kit_li2": "Filtru HEPA lavabil integrat",
        "kit_li3": "Telecomandă + acces aplicație oficială",
        "kit_li4": "Accesorii pentru montaj pe perete",
        "kit_li5": "Manual în română · Livrare 24/48h · Plată ramburs · Retur 14 zile",
        "faq_h2": "Întrebări frecvente",
        "faq": [
            ("Am nevoie de tehnician pentru montaj?", "Nu. Kitul permite montajul în mai puțin de 2 minute, fără lucrări complexe."),
            ("Încălzește și răcește cu adevărat?", "Da. Heaterax™ este 2în1 pentru până la 120 m² cu FastHeating."),
            ("Necesită unitate exterioară sau tub?", "Nu. Funcționează fără unitate exterioară și fără tub de evacuare."),
            ("Cât consumă?", "Clasă energetică <strong>A++++</strong>, consum estimat circa <strong>3,75 lei pe zi</strong>."),
            ("Pot plăti la livrare?", "Da. Plătești ramburs curierului. Pregătește <strong>397 lei</strong>."),
            ("Pot returna produsul?", "Ai 14 zile de la livrare pentru retur, conform politicii site-ului."),
        ],
        "footer_blurb": "Produse utile pentru viața de zi cu zi, livrare 24–48h cu plată ramburs.",
        "footer_info": "Informații",
        "footer_contact": "Contact",
        "footer_rights": "Toate drepturile rezervate.",
        "submitting": "Se trimite...",
        "cookie_text": "Folosim cookie-uri tehnice și de la terți pentru experiență și analiză.",
        "cookie_accept": "Accept",
        "cookie_learn": "Află mai multe",
        "ty_title": "Comandă înregistrată — Așteaptă apelul de confirmare | Heaterax™",
        "ty_desc": "Comanda Heaterax™ a fost înregistrată. Răspunde la apelul operatorului pentru confirmare.",
        "ty_h1": "Comanda ta a fost înregistrată cu succes!",
        "ty_sub": "Perfect — comanda este în procesare. Mai lipsește <strong>un ultim pas</strong> pentru expediere.",
        "ty_action_eyebrow": "👇 Ce trebuie să faci acum",
        "ty_action_title": "📞 Răspunde la apelul de confirmare",
        "ty_action_body": "Un operator te va contacta <strong>în următoarele ore</strong> pentru confirmare.",
        "ty_action_warn": "Dacă nu răspunzi, comanda va fi anulată automat.",
        "ty_hours_h": "🕒 Program contact",
        "ty_hours": "<strong>Luni – Sâmbătă</strong> · 9:00 – 18:00",
        "ty_next_h": "📋 Ce urmează",
        "ty_steps": [
            "Răspunde la apel și <strong>confirmă datele</strong>",
            "Comanda se expediază în <strong>24–48 ore</strong>",
            "Livrare acasă și <strong>plată ramburs</strong>",
        ],
        "ty_trust": ["🔒 Plată la livrare", "🛡️ Garanție 24 luni", "🔐 Protecție SSL"],
    },
    "pt": {
        "brand": "AirCurtain™",
        "header_line1": "Cortina de ar",
        "title": "AirCurtain™ — Climatizador de parede 2 em 1 | -50%",
        "meta_desc": "AirCurtain™: climatizador compacto 2 em 1, FastHeating, classe A++++, pagamento na entrega em Portugal.",
        "ticker_pay": "PAGAMENTO",
        "ticker_cod": "PAGA NA ENTREGA",
        "ticker_guarantee": "GARANTIA",
        "ticker_refund": "SATISFEITO OU REEMBOLSADO · 14 DIAS",
        "reviews_link": "★ Avaliações",
        "order_cta": "↗ Encomendar",
        "h1": "O cortina de ar compacta inovadora 2 em 1 sem unidade exterior que refresca no verão e aquece no inverno — sem instalações caras!",
        "lead": "A tecnologia <strong>FastHeating</strong> distribui o ar rapidamente para conforto uniforme. Classe <strong>A++++</strong> e funcionamento <strong>ultra silencioso</strong> de dia e de noite.",
        "checklist": [
            "Aquece ou refresca até 120 m² em 8 minutos",
            "Consome cerca de 0,75 € por dia, classe A++++",
            "Instala-se em menos de 2 minutos, sem técnico",
            "Design compacto, apenas 55 cm de largura",
            "Funciona sem unidade exterior nem tubo de evacuação",
            "FastHeating leva o ambiente à temperatura desejada rapidamente",
            "Ultra silencioso — conforto também à noite",
            "Filtro HEPA lavável retém 99,99% de germes e bactérias",
            "Controlo por app oficial ou comando",
            "Depósito de condensação 10 L, fácil de esvaziar",
        ],
        "rating": "Avaliação média: <strong>4,8 / 5</strong> · mais de <strong>4.200</strong> avaliações verificadas",
        "countdown_label": "● OFERTA A TERMINAR",
        "countdown_sub": "Termina hoje às <strong>23:59</strong>",
        "offer_h2": "Só hoje o climatizador <span class=\"brand\">AirCurtain™</span>",
        "offer_sub": "🚚 Entrega 24/48h + Garantia 14 dias satisfeito ou reembolsado",
        "price_label": "Por apenas",
        "discount": "− 50% de desconto",
        "scroll_hint": "Preenche o formulário abaixo para encomendar",
        "stock_badge": "STOCK LIMITADO",
        "stock_warn": "<strong>Despacha-te:</strong> restam apenas <strong>18 unidades</strong>!",
        "live": "<strong>{n} pessoas</strong> estão a encomendar AirCurtain agora",
        "form_h3": "Preenche o formulário de encomenda",
        "form_intro": "Contactamos-te para confirmar entrega e pagamento na entrega.",
        "label_name": "Nome completo*",
        "label_tel": "Telemóvel*",
        "label_addr": "Morada de entrega*",
        "ph_name": "João Silva",
        "ph_tel": "+351 912 345 678",
        "ph_addr": "Rua Augusta 10, 1100-053 Lisboa",
        "submit": "Confirmar encomenda",
        "form_trust": "🔒 Dados protegidos · Sem pagamento online · Entrega 24/48h",
        "trust1": "🛡️ Pagamento na entrega",
        "trust2": "🚚 Entrega 24/48h",
        "trust3": "↩️ Devolução gratuita",
        "story1_eyebrow": "01 — Conforto em 13 minutos",
        "story1_h3": "Quente no inverno, fresco no verão",
        "story1_p1": "<strong>AirCurtain™</strong> aquece ou refresca até <strong>85 m²</strong> em <strong>13 minutos</strong> com <strong>FastHeating</strong>.",
        "story1_p2": "Define a temperatura e mantém conforto uniforme em casa.",
        "story2_eyebrow": "02 — Instalação rápida",
        "story2_h3": "Sem obras complicadas",
        "story2_p1": "Com o <strong>kit de montagem rápida</strong>, instalação em menos de <strong>2 minutos</strong>.",
        "story2_p2": "Sem unidade exterior nem tubo — ideal para apartamentos.",
        "story3_eyebrow": "03 — Controlo e manutenção",
        "story3_h3": "Controlo simples e completo",
        "story3_p1": "Comando incluído e <strong>app AirCurtain™</strong>, <strong>ecrã LED</strong> e <strong>temporizador</strong>.",
        "story3_p2": "Depósito de <strong>10 litros</strong> fácil de esvaziar.",
        "reviews_h2": "Avaliações de clientes",
        "reviews_sub": "★ 4,8/5 · Compra verificada",
        "rev1_h": "Instalei sozinha, calor imediato",
        "rev1_p": "«Instalei em casa no Porto sem técnico. Em poucos minutos notei diferença de temperatura e ocupa pouco espaço na parede.»",
        "rev1_a": "Mariana C. ✅ — Porto · Compra verificada",
        "rev2_h": "Silencioso no quarto",
        "rev2_p": "«Uso à noite em Braga e é muito silencioso. O comando é prático — regulo a temperatura da cama.»",
        "rev2_a": "Ricardo F. ✅ — Braga · Compra verificada",
        "rev3_h": "Sem unidade exterior",
        "rev3_p": "«Escolhi porque não precisa de unidade exterior. Montagem simples no apartamento em Coimbra.»",
        "rev3_a": "Sofia L. ✅ — Coimbra · Compra verificada",
        "kit_eyebrow": "O que recebes hoje",
        "kit_h2": "Kit completo AirCurtain™",
        "kit_li1": "<strong>1× AirCurtain™</strong> climatizador 2 em 1 de parede",
        "kit_li2": "Filtro HEPA lavável integrado",
        "kit_li3": "Comando + app oficial",
        "kit_li4": "Acessórios de montagem na parede",
        "kit_li5": "Manual em português · Entrega 24/48h · Pagamento na entrega · Devolução 14 dias",
        "faq_h2": "Perguntas frequentes",
        "faq": [
            ("Preciso de técnico?", "Não. O kit permite instalação em menos de 2 minutos."),
            ("Aquece e refresca mesmo?", "Sim. Dispositivo 2 em 1 até 120 m² com FastHeating."),
            ("Precisa de unidade exterior?", "Não. Funciona sem unidade exterior nem tubo."),
            ("Quanto consome?", "Classe <strong>A++++</strong>, cerca de <strong>0,75 € por dia</strong>."),
            ("Posso pagar na entrega?", "Sim. Pagamento na entrega — prepara <strong>89 €</strong>."),
            ("Posso devolver?", "Tens 14 dias após a entrega, conforme política do site."),
        ],
        "footer_blurb": "Produtos úteis no dia a dia, entrega 24–48h com pagamento na entrega.",
        "footer_info": "Informação",
        "footer_contact": "Contactos",
        "footer_rights": "Todos os direitos reservados.",
        "submitting": "A enviar...",
        "cookie_text": "Usamos cookies técnicos e de terceiros para melhorar a experiência e análise.",
        "cookie_accept": "Aceitar",
        "cookie_learn": "Saber mais",
        "ty_title": "Encomenda recebida — Aguarda a chamada | AirCurtain™",
        "ty_desc": "A tua encomenda AirCurtain™ foi registada. Responde à chamada de confirmação.",
        "ty_h1": "A tua encomenda foi registada com sucesso!",
        "ty_sub": "Falta apenas <strong>um último passo</strong> para concluir e enviar.",
        "ty_action_eyebrow": "👇 O que fazer agora",
        "ty_action_title": "📞 Atende à chamada de confirmação",
        "ty_action_body": "Contactamos-te <strong>nas próximas horas</strong> para confirmar.",
        "ty_action_warn": "Se não atenderes, a encomenda será cancelada automaticamente.",
        "ty_hours_h": "🕒 Horário de contacto",
        "ty_hours": "<strong>Segunda – Sábado</strong> · 9:00 – 18:00",
        "ty_next_h": "📋 Próximos passos",
        "ty_steps": [
            "Atende e <strong>confirma os teus dados</strong>",
            "Envio em <strong>24–48 horas</strong>",
            "Entrega em casa e <strong>pagamento na entrega</strong>",
        ],
        "ty_trust": ["🔒 Pagamento na entrega", "🛡️ Garantia 24 meses", "🔐 SSL"],
    },
    "pl": {
        "brand": "Heaterax™",
        "header_line1": "Klimatyzator",
        "title": "Heaterax™ — Kompaktowy klimatyzator ścienny 2w1 | -50%",
        "meta_desc": "Heaterax™: kompaktowy klimatyzator 2w1, FastHeating, klasa A++++, płatność przy odbiorze w Polsce.",
        "ticker_pay": "PŁATNOŚĆ",
        "ticker_cod": "PŁACISZ PRZY ODBIORZE",
        "ticker_guarantee": "GWARANCJA",
        "ticker_refund": "SATYSFAKCJA LUB ZWROT · 14 DNI",
        "reviews_link": "★ Opinie",
        "order_cta": "↗ Zamów teraz",
        "h1": "Innowacyjny kompaktowy klimatyzator 2w1 bez jednostki zewnętrznej — chłodzi latem i grzeje zimą bez drogiego montażu!",
        "lead": "Technologia <strong>FastHeating</strong> szybko rozprowadza powietrze dla równomiernej temperatury. Klasa <strong>A++++</strong> i praca <strong>ultra cicha</strong> w dzień i w nocy.",
        "checklist": [
            "Grzeje lub chłodzi do 120 m² w 8 minut",
            "Zużywa ok. 3,35 zł dziennie, klasa A++++",
            "Montaż w mniej niż 2 minuty, bez technika",
            "Kompaktowa szerokość 55 cm",
            "Bez jednostki zewnętrznej i bez rury odprowadzającej",
            "FastHeating szybko osiąga temperaturę",
            "Ultra cichy — komfort także w nocy",
            "Filtr HEPA — 99,99% drobnoustrojów",
            "Sterowanie aplikacją lub pilotem",
            "Zbiornik kondensatu 10 L, łatwy do opróżnienia",
        ],
        "rating": "Średnia ocena: <strong>4,8 / 5</strong> · ponad <strong>4 200</strong> opinii",
        "countdown_label": "● OFERTA KOŃCZY SIĘ",
        "countdown_sub": "Do <strong>23:59</strong> dziś",
        "offer_h2": "Tylko dziś klimatyzator <span class=\"brand\">Heaterax™</span>",
        "offer_sub": "🚚 Dostawa 24/48h + 14 dni satysfakcji lub zwrot",
        "price_label": "Tylko",
        "discount": "− 50% rabatu",
        "scroll_hint": "Wypełnij formularz poniżej, aby zamówić",
        "stock_badge": "OGRANICZONA ILOŚĆ",
        "stock_warn": "<strong>Pospiesz się:</strong> zostało tylko <strong>18 sztuk</strong>!",
        "live": "<strong>{n} osób</strong> zamawia Heaterax teraz",
        "form_h3": "Formularz zamówienia",
        "form_intro": "Skontaktujemy się, aby potwierdzić dostawę i płatność przy odbiorze.",
        "label_name": "Imię i nazwisko*",
        "label_tel": "Telefon komórkowy*",
        "label_addr": "Adres dostawy*",
        "ph_name": "Jan Kowalski",
        "ph_tel": "+48 512 345 678",
        "ph_addr": "ul. Marszałkowska 10, 00-001 Warszawa",
        "submit": "Potwierdź zamówienie",
        "form_trust": "🔒 Dane chronione · Bez płatności online · Dostawa 24/48h",
        "trust1": "🛡️ Płatność przy odbiorze",
        "trust2": "🚚 Dostawa 24/48h",
        "trust3": "↩️ Darmowy zwrot",
        "story1_eyebrow": "01 — Komfort w 13 minut",
        "story1_h3": "Ciepło zimą, chłód latem",
        "story1_p1": "<strong>Heaterax™</strong> ogrzewa lub chłodzi do <strong>85 m²</strong> w <strong>13 minut</strong> dzięki <strong>FastHeating</strong>.",
        "story1_p2": "Ustaw temperaturę — komfort w całym mieszkaniu.",
        "story2_eyebrow": "02 — Szybki montaż",
        "story2_h3": "Bez skomplikowanej instalacji",
        "story2_p1": "<strong>Heaterax™</strong> montujesz w <strong>2 minuty</strong> z zestawem ściennym.",
        "story2_p2": "Bez jednostki zewnętrznej — idealny do bloków.",
        "story3_eyebrow": "03 — Sterowanie",
        "story3_h3": "Pełna kontrola",
        "story3_p1": "Pilot, <strong>aplikacja Heaterax™</strong>, <strong>LED</strong> i <strong>timer</strong>.",
        "story3_p2": "Zbiornik <strong>10 l</strong> łatwy do opróżnienia.",
        "reviews_h2": "Opinie klientów",
        "reviews_sub": "★ 4,8/5 · Zweryfikowany zakup",
        "rev1_h": "Samodzielny montaż, szybkie ciepło",
        "rev1_p": "«Zamontowałam sama w Krakowie — bez fachowca. Temperatura rośnie szybko, urządzenie zajmuje mało miejsca.»",
        "rev1_a": "Katarzyna W. ✅ — Kraków · Zweryfikowany zakup",
        "rev2_h": "Cicho w sypialni",
        "rev2_p": "«W Gdańsku używam wieczorem — bardzo cicho. Pilot prosty, reguluję z łóżka.»",
        "rev2_a": "Tomasz K. ✅ — Gdańsk · Zweryfikowany zakup",
        "rev3_h": "Bez jednostki zewnętrznej",
        "rev3_p": "«W Poznaniu wybrałam go właśnie dlatego — montaż prosty, bez dużych otworów.»",
        "rev3_a": "Magdalena L. ✅ — Poznań · Zweryfikowany zakup",
        "kit_eyebrow": "Co otrzymujesz dziś",
        "kit_h2": "Pełny zestaw Heaterax™",
        "kit_li1": "<strong>1× Heaterax™</strong> klimatyzator ścienny 2w1",
        "kit_li2": "Filtr HEPA do prania",
        "kit_li3": "Pilot + aplikacja",
        "kit_li4": "Akcesoria montażowe",
        "kit_li5": "Instrukcja PL · Dostawa 24/48h · Pobranie · Zwrot 14 dni",
        "faq_h2": "FAQ",
        "faq": [
            ("Czy potrzebuję technika?", "Nie — montaż poniżej 2 minut."),
            ("Czy grzeje i chłodzi?", "Tak, 2w1 do 120 m² z FastHeating."),
            ("Jednostka zewnętrzna?", "Nie jest potrzebna."),
            ("Zużycie?", "Klasa <strong>A++++</strong>, ok. <strong>3,35 zł/dzień</strong>."),
            ("Pobranie?", "Tak — przygotuj <strong>299 zł</strong>."),
            ("Zwrot?", "14 dni od dostawy według regulaminu."),
        ],
        "footer_blurb": "Praktyczne produkty, dostawa 24–48h, płatność przy odbiorze.",
        "footer_info": "Informacje",
        "footer_contact": "Kontakt",
        "footer_rights": "Wszelkie prawa zastrzeżone.",
        "submitting": "Wysyłanie...",
        "cookie_text": "Używamy plików cookie technicznych i analitycznych.",
        "cookie_accept": "Akceptuję",
        "cookie_learn": "Więcej",
        "ty_title": "Zamówienie przyjęte | Heaterax™",
        "ty_desc": "Zamówienie Heaterax™ zarejestrowane — odbierz telefon potwierdzający.",
        "ty_h1": "Zamówienie zostało zarejestrowane!",
        "ty_sub": "Brakuje <strong>ostatniego kroku</strong> przed wysyłką.",
        "ty_action_eyebrow": "👇 Co teraz",
        "ty_action_title": "📞 Odbierz telefon potwierdzający",
        "ty_action_body": "Operator zadzwoni <strong>w najbliższych godzinach</strong>.",
        "ty_action_warn": "Brak odpowiedzi = anulowanie zamówienia.",
        "ty_hours_h": "🕒 Godziny kontaktu",
        "ty_hours": "<strong>Pon.–Sob.</strong> · 9:00–18:00",
        "ty_next_h": "📋 Co dalej",
        "ty_steps": ["Odbierz i <strong>potwierdź dane</strong>", "Wysyłka w <strong>24–48 h</strong>", "<strong>Płatność przy odbiorze</strong>"],
        "ty_trust": ["🔒 Pobranie", "🛡️ Gwarancja 24 mies.", "🔐 SSL"],
    },
    "es": {
        "brand": "AirCurtain™",
        "header_line1": "Cortina de aire",
        "title": "AirCurtain™ — Climatizador de pared 2 en 1 | -50%",
        "meta_desc": "AirCurtain™: climatizador compacto 2 en 1, FastHeating, clase A++++, pago contra reembolso en España.",
        "ticker_pay": "PAGO",
        "ticker_cod": "PAGA AL RECIBIR",
        "ticker_guarantee": "GARANTÍA",
        "ticker_refund": "SATISFECHO O REEMBOLSADO · 14 DÍAS",
        "reviews_link": "★ Reseñas",
        "order_cta": "↗ Pedir ahora",
        "h1": "¡El innovador climatizador compacto 2 en 1 sin unidad exterior que refresca en verano y calienta en invierno, sin instalaciones caras!",
        "lead": "La tecnología <strong>FastHeating</strong> distribuye el aire rápidamente. Clase <strong>A++++</strong> y funcionamiento <strong>ultrasilencioso</strong>.",
        "checklist": [
            "Calienta o enfría hasta 120 m² en 8 minutos",
            "Consumo aprox. 0,75 € al día, clase A++++",
            "Instalación en menos de 2 minutos, sin técnico",
            "Diseño compacto de 55 cm",
            "Sin unidad exterior ni tubo de evacuación",
            "FastHeating alcanza la temperatura rápidamente",
            "Ultrasilencioso de noche",
            "Filtro HEPA lavable — 99,99% de gérmenes",
            "Control por app o mando",
            "Depósito de condensados 10 L",
        ],
        "rating": "Valoración media: <strong>4,8 / 5</strong> · más de <strong>4.200</strong> reseñas",
        "countdown_label": "● OFERTA TERMINA",
        "countdown_sub": "Hoy a las <strong>23:59</strong>",
        "offer_h2": "Solo hoy el climatizador <span class=\"brand\">AirCurtain™</span>",
        "offer_sub": "🚚 Entrega 24/48h + 14 días satisfecho o reembolsado",
        "price_label": "Por solo",
        "discount": "− 50% de descuento",
        "scroll_hint": "Completa el formulario para pedir",
        "stock_badge": "STOCK LIMITADO",
        "stock_warn": "<strong>Date prisa:</strong> ¡solo quedan <strong>18 unidades</strong>!",
        "live": "<strong>{n} personas</strong> están pidiendo AirCurtain ahora",
        "form_h3": "Formulario de pedido",
        "form_intro": "Te llamamos para confirmar envío y pago contra reembolso.",
        "label_name": "Nombre y apellidos*",
        "label_tel": "Móvil*",
        "label_addr": "Dirección de envío*",
        "ph_name": "María García",
        "ph_tel": "+34 612 345 678",
        "ph_addr": "Calle Gran Vía 10, 28013 Madrid",
        "submit": "Confirmar pedido",
        "form_trust": "🔒 Datos protegidos · Sin pago online · Envío 24/48h",
        "trust1": "🛡️ Pago al recibir",
        "trust2": "🚚 Envío 24/48h",
        "trust3": "↩️ Devolución gratuita",
        "story1_eyebrow": "01 — Confort en 13 minutos",
        "story1_h3": "Calor en invierno, fresco en verano",
        "story1_p1": "<strong>AirCurtain™</strong> climatiza hasta <strong>85 m²</strong> en <strong>13 minutos</strong>.",
        "story1_p2": "Confort rápido en todo el piso.",
        "story2_eyebrow": "02 — Instalación rápida",
        "story2_h3": "Sin obras complicadas",
        "story2_p1": "Montaje en <strong>2 minutos</strong> con kit incluido.",
        "story2_p2": "Sin unidad exterior — ideal en pisos.",
        "story3_eyebrow": "03 — Control",
        "story3_h3": "Control sencillo",
        "story3_p1": "Mando, <strong>app AirCurtain™</strong>, <strong>LED</strong> y <strong>temporizador</strong>.",
        "story3_p2": "Depósito de <strong>10 litros</strong> fácil de vaciar.",
        "reviews_h2": "Opiniones de clientes",
        "reviews_sub": "★ 4,8/5 · Compra verificada",
        "rev1_h": "Instalé yo sola, calor al instante",
        "rev1_p": "«Lo instalé en Valencia sin técnico. Se nota el calor enseguida y ocupa poco en la pared.»",
        "rev1_a": "Elena V. ✅ — Valencia · Compra verificada",
        "rev2_h": "Silencioso en el dormitorio",
        "rev2_p": "«En Sevilla lo uso por la noche — muy silencioso. Regulo la temperatura desde la cama.»",
        "rev2_a": "Marcos L. ✅ — Sevilla · Compra verificada",
        "rev3_h": "Sin unidad exterior",
        "rev3_p": "«En Barcelona lo elegí porque no necesita unidad exterior. Montaje sencillo.»",
        "rev3_a": "Lucía H. ✅ — Barcelona · Compra verificada",
        "kit_eyebrow": "Qué recibes hoy",
        "kit_h2": "Kit completo AirCurtain™",
        "kit_li1": "<strong>1× AirCurtain™</strong> climatizador 2 en 1 de pared",
        "kit_li2": "Filtro HEPA lavable",
        "kit_li3": "Mando + app oficial",
        "kit_li4": "Accesorios de montaje",
        "kit_li5": "Manual en español · Envío 24/48h · Contra reembolso · 14 días devolución",
        "faq_h2": "Preguntas frecuentes",
        "faq": [
            ("¿Necesito técnico?", "No — montaje en menos de 2 minutos."),
            ("¿Calienta y enfría?", "Sí, 2 en 1 hasta 120 m²."),
            ("¿Unidad exterior?", "No hace falta."),
            ("¿Consumo?", "Clase <strong>A++++</strong>, ~<strong>0,75 €/día</strong>."),
            ("¿Contra reembolso?", "Sí — ten listos <strong>89 €</strong>."),
            ("¿Devolución?", "14 días según política del sitio."),
        ],
        "footer_blurb": "Productos útiles, entrega 24–48h, pago al recibir.",
        "footer_info": "Información",
        "footer_contact": "Contacto",
        "footer_rights": "Todos los derechos reservados.",
        "submitting": "Enviando...",
        "cookie_text": "Usamos cookies técnicas y de análisis.",
        "cookie_accept": "Aceptar",
        "cookie_learn": "Más info",
        "ty_title": "Pedido recibido | AirCurtain™",
        "ty_desc": "Pedido AirCurtain™ registrado — responde a la llamada de confirmación.",
        "ty_h1": "¡Tu pedido se ha registrado correctamente!",
        "ty_sub": "Falta <strong>un último paso</strong> para enviarlo.",
        "ty_action_eyebrow": "👇 Qué hacer ahora",
        "ty_action_title": "📞 Responde a la llamada de confirmación",
        "ty_action_body": "Te llamamos <strong>en las próximas horas</strong>.",
        "ty_action_warn": "Si no respondes, el pedido se cancelará.",
        "ty_hours_h": "🕒 Horario de contacto",
        "ty_hours": "<strong>Lunes – Sábado</strong> · 9:00 – 18:00",
        "ty_next_h": "📋 Próximos pasos",
        "ty_steps": ["Responde y <strong>confirma tus datos</strong>", "Envío en <strong>24–48 h</strong>", "<strong>Pago al recibir</strong>"],
        "ty_trust": ["🔒 Contra reembolso", "🛡️ Garantía 24 meses", "🔐 SSL"],
    },
    "de": {
        "brand": "AirCurtain™",
        "header_line1": "Luftvorhang",
        "title": "AirCurtain™ — Wand-Klimagerät 2in1 | -50%",
        "meta_desc": "AirCurtain™: kompaktes 2in1-Wandklimagerät, FastHeating, A++++, Nachnahme in Deutschland.",
        "ticker_pay": "ZAHLUNG",
        "ticker_cod": "ZAHLUNG BEI LIEFERUNG",
        "ticker_guarantee": "GARANTIE",
        "ticker_refund": "ZUFRIEDEN ODER GELD ZURÜCK · 14 TAGE",
        "reviews_link": "★ Bewertungen",
        "order_cta": "↗ Jetzt bestellen",
        "h1": "Das innovative kompakte 2in1-Wandklimagerät ohne Außengerät — kühlt im Sommer und heizt im Winter, ohne teure Installation!",
        "lead": "<strong>FastHeating</strong> verteilt die Luft schnell für gleichmäßige Temperatur. Energieklasse <strong>A++++</strong>, <strong>ultra leise</strong>.",
        "checklist": [
            "Heizt oder kühlt bis 120 m² in 8 Minuten",
            "Ca. 0,75 € pro Tag, Klasse A++++",
            "Montage in unter 2 Minuten, ohne Techniker",
            "Kompakt, nur 55 cm breit",
            "Ohne Außengerät und ohne Ablaufschlauch",
            "FastHeating erreicht schnell die Solltemperatur",
            "Ultra leise — auch nachts",
            "Waschbarer HEPA-Filter — 99,99% Keime",
            "Steuerung per App oder Fernbedienung",
            "10-L-Kondensattank, leicht zu entleeren",
        ],
        "rating": "Durchschnitt: <strong>4,8 / 5</strong> · über <strong>4.200</strong> Bewertungen",
        "countdown_label": "● ANGEBOT ENDET",
        "countdown_sub": "Heute um <strong>23:59</strong>",
        "offer_h2": "Nur heute das Klimagerät <span class=\"brand\">AirCurtain™</span>",
        "offer_sub": "🚚 Lieferung 24/48h + 14 Tage Zufriedenheitsgarantie",
        "price_label": "Nur",
        "discount": "− 50% Rabatt",
        "scroll_hint": "Formular unten ausfüllen zum Bestellen",
        "stock_badge": "LIMITIERTER BESTAND",
        "stock_warn": "<strong>Beeilen Sie sich:</strong> nur noch <strong>18 Stück</strong>!",
        "live": "<strong>{n} Personen</strong> bestellen gerade AirCurtain",
        "form_h3": "Bestellformular",
        "form_intro": "Wir rufen an, um Lieferung und Nachnahme zu bestätigen.",
        "label_name": "Vor- und Nachname*",
        "label_tel": "Handynummer*",
        "label_addr": "Lieferadresse*",
        "ph_name": "Anna Müller",
        "ph_tel": "+49 151 23456789",
        "ph_addr": "Hauptstraße 10, 10115 Berlin",
        "submit": "Bestellung bestätigen",
        "form_trust": "🔒 Daten geschützt · Keine Online-Zahlung · Lieferung 24/48h",
        "trust1": "🛡️ Zahlung bei Lieferung",
        "trust2": "🚚 Lieferung 24/48h",
        "trust3": "↩️ Kostenlose Rückgabe",
        "story1_eyebrow": "01 — Komfort in 13 Minuten",
        "story1_h3": "Warm im Winter, kühl im Sommer",
        "story1_p1": "<strong>AirCurtain™</strong> für bis <strong>85 m²</strong> in <strong>13 Minuten</strong> mit <strong>FastHeating</strong>.",
        "story1_p2": "Schneller, gleichmäßiger Komfort in der Wohnung.",
        "story2_eyebrow": "02 — Schnelle Montage",
        "story2_h3": "Keine komplizierte Installation",
        "story2_p1": "Montage in <strong>unter 2 Minuten</strong> mit Wand-Kit.",
        "story2_p2": "Ohne Außengerät — ideal für Mietwohnungen.",
        "story3_eyebrow": "03 — Steuerung",
        "story3_h3": "Einfache Bedienung",
        "story3_p1": "Fernbedienung, <strong>AirCurtain™ App</strong>, <strong>LED</strong> und <strong>Timer</strong>.",
        "story3_p2": "<strong>10-Liter</strong>-Tank leicht entleerbar.",
        "reviews_h2": "Kundenbewertungen",
        "reviews_sub": "★ 4,8/5 · Verifizierter Kauf",
        "rev1_h": "Allein montiert, sofort spürbar warm",
        "rev1_p": "«In München selbst montiert — ohne Techniker. Temperatur schnell spürbar, sehr platzsparend.»",
        "rev1_a": "Sandra M. ✅ — München · Verifizierter Kauf",
        "rev2_h": "Leise im Schlafzimmer",
        "rev2_p": "«Abends in Hamburg im Schlafzimmer — überraschend leise. Fernbedienung vom Bett aus.»",
        "rev2_a": "Thomas B. ✅ — Hamburg · Verifizierter Kauf",
        "rev3_h": "Ohne Außengerät",
        "rev3_p": "«In Köln wegen fehlendem Außengerät gewählt — einfache Montage.»",
        "rev3_a": "Julia K. ✅ — Köln · Verifizierter Kauf",
        "kit_eyebrow": "Heute erhalten Sie",
        "kit_h2": "Komplett-Set AirCurtain™",
        "kit_li1": "<strong>1× AirCurtain™</strong> 2in1 Wandgerät",
        "kit_li2": "Integrierter HEPA-Filter",
        "kit_li3": "Fernbedienung + App",
        "kit_li4": "Wandmontage-Zubehör",
        "kit_li5": "Anleitung DE · Lieferung 24/48h · Nachnahme · 14 Tage Rückgabe",
        "faq_h2": "Häufige Fragen",
        "faq": [
            ("Techniker nötig?", "Nein — Montage unter 2 Minuten."),
            ("Heizt und kühlt es?", "Ja, 2in1 bis 120 m²."),
            ("Außengerät?", "Nicht erforderlich."),
            ("Verbrauch?", "Klasse <strong>A++++</strong>, ca. <strong>0,75 €/Tag</strong>."),
            ("Nachnahme?", "Ja — <strong>89 €</strong> bereithalten."),
            ("Rückgabe?", "14 Tage laut Richtlinie."),
        ],
        "footer_blurb": "Nützliche Produkte, Lieferung 24–48h, Zahlung bei Lieferung.",
        "footer_info": "Informationen",
        "footer_contact": "Kontakt",
        "footer_rights": "Alle Rechte vorbehalten.",
        "submitting": "Wird gesendet...",
        "cookie_text": "Wir verwenden technische und Analyse-Cookies.",
        "cookie_accept": "Akzeptieren",
        "cookie_learn": "Mehr erfahren",
        "ty_title": "Bestellung erhalten | AirCurtain™",
        "ty_desc": "AirCurtain™ Bestellung registriert — Bestätigungsanruf beantworten.",
        "ty_h1": "Ihre Bestellung wurde erfolgreich registriert!",
        "ty_sub": "Nur noch <strong>ein Schritt</strong> bis zum Versand.",
        "ty_action_eyebrow": "👇 Jetzt erforderlich",
        "ty_action_title": "📞 Bestätigungsanruf annehmen",
        "ty_action_body": "Wir rufen <strong>in den nächsten Stunden</strong> an.",
        "ty_action_warn": "Ohne Annahme wird die Bestellung storniert.",
        "ty_hours_h": "🕒 Kontaktzeiten",
        "ty_hours": "<strong>Mo–Sa</strong> · 9:00–18:00",
        "ty_next_h": "📋 Nächste Schritte",
        "ty_steps": ["Anruf annehmen und <strong>Daten bestätigen</strong>", "Versand in <strong>24–48 Std.</strong>", "<strong>Zahlung bei Lieferung</strong>"],
        "ty_trust": ["🔒 Nachnahme", "🛡️ 24 Mon. Garantie", "🔐 SSL"],
    },
    "hu": {
        "brand": "Heaterax™",
        "header_line1": "Klíma",
        "title": "Heaterax™ — Falra szerelhető 2 az 1-ben klíma | -50%",
        "meta_desc": "Heaterax™: kompakt 2 az 1-ben faliklima, FastHeating, A++++, utánvétes fizetés Magyarországon.",
        "ticker_pay": "FIZETÉS",
        "ticker_cod": "UTÁNVÉT",
        "ticker_guarantee": "GARANCIA",
        "ticker_refund": "ELÉGEDETTSÉG VAGY PÉNZVISSZAFIZETÉS · 14 NAP",
        "reviews_link": "★ Vélemények",
        "order_cta": "↗ Rendelés",
        "h1": "Az innovatív kompakt 2 az 1-ben faliklima külső egység nélkül — nyáron hűt, télen fűt, drága szerelés nélkül!",
        "lead": "A <strong>FastHeating</strong> gyorsan elosztja a levegőt. <strong>A++++</strong> energiaosztály, <strong>ultra csendes</strong> működés.",
        "checklist": [
            "Akár 120 m² fűtése/hűtése 8 perc alatt",
            "Napi kb. 320 Ft fogyasztás, A++++",
            "2 perc alatt felszerelhető, szerelő nélkül",
            "Kompakt, 55 cm széles",
            "Külső egység és lefolyócső nélkül",
            "FastHeating — gyors hőmérséklet",
            "Ultra csendes éjjel is",
            "Mosható HEPA szűrő — 99,99%",
            "App vagy távirányító",
            "10 L kondenzvíz-tartály",
        ],
        "rating": "Átlag: <strong>4,8 / 5</strong> · több mint <strong>4 200</strong> vélemény",
        "countdown_label": "● AZ AJÁNLAT LEJÁR",
        "countdown_sub": "Ma <strong>23:59</strong>-ig",
        "offer_h2": "Csak ma a <span class=\"brand\">Heaterax™</span> klíma",
        "offer_sub": "🚚 Szállítás 24/48h + 14 napos elégedettségi garancia",
        "price_label": "Mindössze",
        "discount": "− 50% kedvezmény",
        "scroll_hint": "Töltsd ki az űrlapot a rendeléshez",
        "stock_badge": "KORLÁTOZOTT KÉSZLET",
        "stock_warn": "<strong>Siess:</strong> már csak <strong>18 db</strong> van raktáron!",
        "live": "<strong>{n} ember</strong> rendeli épp a Heateraxot",
        "form_h3": "Rendelési űrlap",
        "form_intro": "Felhívunk a szállítás és utánvét megerősítéséhez.",
        "label_name": "Teljes név*",
        "label_tel": "Mobilszám*",
        "label_addr": "Szállítási cím*",
        "ph_name": "Kovács Anna",
        "ph_tel": "+36 30 123 4567",
        "ph_addr": "Andrássy út 10, 1061 Budapest",
        "submit": "Rendelés megerősítése",
        "form_trust": "🔒 Védett adatok · Nincs online fizetés · 24/48h szállítás",
        "trust1": "🛡️ Utánvét",
        "trust2": "🚚 24/48h szállítás",
        "trust3": "↩️ Ingyenes visszaküldés",
        "story1_eyebrow": "01 — Komfort 13 perc alatt",
        "story1_h3": "Meleg télen, hűvös nyáron",
        "story1_p1": "<strong>Heaterax™</strong> akár <strong>85 m²</strong>-et <strong>13 perc</strong> alatt, <strong>FastHeating</strong> technológiával.",
        "story1_p2": "Gyors, egyenletes komfort az egész lakásban.",
        "story2_eyebrow": "02 — Gyors felszerelés",
        "story2_h3": "Bonyolult szerelés nélkül",
        "story2_p1": "<strong>2 perc</strong> alatt felszerelhető falikészlettel.",
        "story2_p2": "Külső egység nélkül — tömbházba is ideális.",
        "story3_eyebrow": "03 — Vezérlés",
        "story3_h3": "Egyszerű teljes kontroll",
        "story3_p1": "Távirányító, <strong>Heaterax™ app</strong>, <strong>LED</strong> és <strong>időzítő</strong>.",
        "story3_p2": "<strong>10 literes</strong> tartály könnyen üríthető.",
        "reviews_h2": "Vásárlói vélemények",
        "reviews_sub": "★ 4,8/5 · Ellenőrzött vásárlás",
        "rev1_h": "Egyedül szereltem fel, azonnali meleg",
        "rev1_p": "«Debrecenben egyedül raktam fel technikus nélkül. Gyorsan érezni a hőt, kevés helyet foglal.»",
        "rev1_a": "Nagy Eszter ✅ — Debrecen · Ellenőrzött vásárlás",
        "rev2_h": "Csendes a hálószobában",
        "rev2_p": "«Szegeden esténként is használom — meglepően csendes. Ágyból állítom a hőmérsékletet.»",
        "rev2_a": "Horváth Péter ✅ — Szeged · Ellenőrzött vásárlás",
        "rev3_h": "Külső egység nélkül",
        "rev3_p": "«Pécsett emiatt választottam — egyszerű felszerelés, nagy furakodás nélkül.»",
        "rev3_a": "Tóth Zita ✅ — Pécs · Ellenőrzött vásárlás",
        "kit_eyebrow": "Mit kapsz ma",
        "kit_h2": "Teljes Heaterax™ csomag",
        "kit_li1": "<strong>1× Heaterax™</strong> 2 az 1-ben faliklima",
        "kit_li2": "Beépített mosható HEPA szűrő",
        "kit_li3": "Távirányító + hivatalos app",
        "kit_li4": "Falra szerelési kellékek",
        "kit_li5": "Magyar útmutató · 24/48h · Utánvét · 14 nap visszaküldés",
        "faq_h2": "Gyakori kérdések",
        "faq": [
            ("Kell szerelő?", "Nem — 2 perc alatt felszerelhető."),
            ("Tényleg fűt és hűt?", "Igen, 2 az 1-ben akár 120 m²."),
            ("Külső egység?", "Nem szükséges."),
            ("Fogyasztás?", "<strong>A++++</strong>, kb. <strong>320 Ft/nap</strong>."),
            ("Utánvét?", "Igen — készíts <strong>29 999 Ft</strong>-ot."),
            ("Visszaküldés?", "14 nap a kézbesítéstől."),
        ],
        "footer_blurb": "Hasznos termékek, 24–48 órás szállítás, utánvét.",
        "footer_info": "Információ",
        "footer_contact": "Kapcsolat",
        "footer_rights": "Minden jog fenntartva.",
        "submitting": "Küldés...",
        "cookie_text": "Technikai és analitikai sütiket használunk.",
        "cookie_accept": "Elfogadom",
        "cookie_learn": "További info",
        "ty_title": "Rendelés rögzítve | Heaterax™",
        "ty_desc": "Heaterax™ rendelésed rögzítve — vedd fel a megerősítő hívást.",
        "ty_h1": "A rendelésed sikeresen rögzítve!",
        "ty_sub": "Már csak <strong>egy lépés</strong> a szállításig.",
        "ty_action_eyebrow": "👇 Most teendő",
        "ty_action_title": "📞 Vedd fel a megerősítő hívást",
        "ty_action_body": "<strong>A következő órákban</strong> hívunk.",
        "ty_action_warn": "Ha nem veszed fel, a rendelés törlődik.",
        "ty_hours_h": "🕒 Elérhetőség",
        "ty_hours": "<strong>H–Szo</strong> · 9:00–18:00",
        "ty_next_h": "📋 Mi történik ezután",
        "ty_steps": ["Vedd fel és <strong>erősítsd meg az adatokat</strong>", "Szállítás <strong>24–48 órán</strong> belül", "<strong>Utánvét</strong>"],
        "ty_trust": ["🔒 Utánvét", "🛡️ 24 hó garancia", "🔐 SSL"],
    },
}
